// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
void ui_event_Panel1(lv_event_t * e);
lv_obj_t * ui_Panel1;
void ui_event_ImgButton3(lv_event_t * e);
lv_obj_t * ui_ImgButton3;
lv_obj_t * ui_Bar1;
lv_obj_t * ui_Bar2;
lv_obj_t * ui_Bar3;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Panel2;
void ui_event_ImgButton2(lv_event_t * e);
lv_obj_t * ui_ImgButton2;
lv_obj_t * ui_Bar4;
lv_obj_t * ui_Bar5;
lv_obj_t * ui_Bar6;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Panel4;
void ui_event_ImgButton4(lv_event_t * e);
lv_obj_t * ui_ImgButton4;
lv_obj_t * ui_Bar7;
lv_obj_t * ui_Bar13;
lv_obj_t * ui_Bar14;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Panel5;
void ui_event_ImgButton5(lv_event_t * e);
lv_obj_t * ui_ImgButton5;
lv_obj_t * ui_Bar9;
lv_obj_t * ui_Bar15;
lv_obj_t * ui_Bar16;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Panel6;
void ui_event_ImgButton6(lv_event_t * e);
lv_obj_t * ui_ImgButton6;
lv_obj_t * ui_Bar8;
lv_obj_t * ui_Bar17;
lv_obj_t * ui_Bar18;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Panel8;
void ui_event_ImgButton7(lv_event_t * e);
lv_obj_t * ui_ImgButton7;
lv_obj_t * ui_Bar10;
lv_obj_t * ui_Bar19;
lv_obj_t * ui_Bar20;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Panel3;
void ui_event_ImgButton8(lv_event_t * e);
lv_obj_t * ui_ImgButton8;
lv_obj_t * ui_Bar11;
lv_obj_t * ui_Bar21;
lv_obj_t * ui_Bar22;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Panel7;
void ui_event_ImgButton9(lv_event_t * e);
lv_obj_t * ui_ImgButton9;
lv_obj_t * ui_Bar12;
lv_obj_t * ui_Bar23;
lv_obj_t * ui_Bar24;
lv_obj_t * ui_Label3;

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
lv_obj_t * ui_Screen2;
lv_obj_t * ui_Panel9;
void ui_event_Slider2(lv_event_t * e);
lv_obj_t * ui_Slider2;
lv_obj_t * ui_Bar25;
void ui_event_Slider1(lv_event_t * e);
lv_obj_t * ui_Slider1;
lv_obj_t * ui_Bar26;
void ui_event_Slider3(lv_event_t * e);
lv_obj_t * ui_Slider3;
lv_obj_t * ui_Panel10;
void ui_event_Slider4(lv_event_t * e);
lv_obj_t * ui_Slider4;
lv_obj_t * ui_Bar28;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Label20;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label9;
void ui_event_ImgButton10(lv_event_t * e);
lv_obj_t * ui_ImgButton10;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Label19;

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
lv_obj_t * ui_ImgButton1;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_[2] = {&ui_img_5700554_png, &ui_img_6875758_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Panel1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        Ch1Pressed(e);
    }
}
void ui_event_ImgButton3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        Ch1Pressed(e);
    }
}
void ui_event_ImgButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        Ch2Pressed(e);
    }
}
void ui_event_ImgButton4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        Ch3Pressed(e);
    }
}
void ui_event_ImgButton5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        Ch4Pressed(e);
    }
}
void ui_event_ImgButton6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        Ch5Pressed(e);
    }
}
void ui_event_ImgButton7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        Ch6Pressed(e);
    }
}
void ui_event_ImgButton8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        Ch7Pressed(e);
    }
}
void ui_event_ImgButton9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        Ch8Pressed(e);
    }
}
void ui_event_Slider2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        micValueChanged(e);
    }
}
void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        refValueChanged(e);
    }
}
void ui_event_Slider3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        bypassValueChanged(e);
    }
}
void ui_event_Slider4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        outValueChanged(e);
    }
}
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        applyToAllChanPressed(e);
    }
}
void ui_event_ImgButton10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        backButtonPressed(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
