// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_Panel1(lv_event_t * e);
extern lv_obj_t * ui_Panel1;
void ui_event_ImgButton3(lv_event_t * e);
extern lv_obj_t * ui_ImgButton3;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Bar2;
extern lv_obj_t * ui_Bar3;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Panel2;
void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui_Bar4;
extern lv_obj_t * ui_Bar5;
extern lv_obj_t * ui_Bar6;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel4;
void ui_event_ImgButton4(lv_event_t * e);
extern lv_obj_t * ui_ImgButton4;
extern lv_obj_t * ui_Bar7;
extern lv_obj_t * ui_Bar13;
extern lv_obj_t * ui_Bar14;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Panel5;
void ui_event_ImgButton5(lv_event_t * e);
extern lv_obj_t * ui_ImgButton5;
extern lv_obj_t * ui_Bar9;
extern lv_obj_t * ui_Bar15;
extern lv_obj_t * ui_Bar16;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Panel6;
void ui_event_ImgButton6(lv_event_t * e);
extern lv_obj_t * ui_ImgButton6;
extern lv_obj_t * ui_Bar8;
extern lv_obj_t * ui_Bar17;
extern lv_obj_t * ui_Bar18;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel8;
void ui_event_ImgButton7(lv_event_t * e);
extern lv_obj_t * ui_ImgButton7;
extern lv_obj_t * ui_Bar10;
extern lv_obj_t * ui_Bar19;
extern lv_obj_t * ui_Bar20;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel3;
void ui_event_ImgButton8(lv_event_t * e);
extern lv_obj_t * ui_ImgButton8;
extern lv_obj_t * ui_Bar11;
extern lv_obj_t * ui_Bar21;
extern lv_obj_t * ui_Bar22;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Panel7;
void ui_event_ImgButton9(lv_event_t * e);
extern lv_obj_t * ui_ImgButton9;
extern lv_obj_t * ui_Bar12;
extern lv_obj_t * ui_Bar23;
extern lv_obj_t * ui_Bar24;
extern lv_obj_t * ui_Label3;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel9;
void ui_event_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Bar25;
void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Bar26;
void ui_event_Slider3(lv_event_t * e);
extern lv_obj_t * ui_Slider3;
extern lv_obj_t * ui_Panel10;
void ui_event_Slider4(lv_event_t * e);
extern lv_obj_t * ui_Slider4;
extern lv_obj_t * ui_Bar28;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label20;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label9;
void ui_event_ImgButton10(lv_event_t * e);
extern lv_obj_t * ui_ImgButton10;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label19;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_6875758_png);    // assets\6875758.png
LV_IMG_DECLARE(ui_img_5700554_png);    // assets\5700554.png
LV_IMG_DECLARE(ui_img_hal_png);    // assets\HAL.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
