// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Ch1Pressed(lv_event_t * e);
void Ch2Pressed(lv_event_t * e);
void Ch3Pressed(lv_event_t * e);
void Ch4Pressed(lv_event_t * e);
void Ch5Pressed(lv_event_t * e);
void Ch6Pressed(lv_event_t * e);
void Ch7Pressed(lv_event_t * e);
void Ch8Pressed(lv_event_t * e);
void micValueChanged(lv_event_t * e);
void refValueChanged(lv_event_t * e);
void bypassValueChanged(lv_event_t * e);
void outValueChanged(lv_event_t * e);
void applyToAllChanPressed(lv_event_t * e);
void backButtonPressed(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
