// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

// void Ch1Pressed(lv_event_t * e)
// {
// 	// Your code here
// }

// void applyToAllChanPressed(lv_event_t * e)
// {
// 	// Your code here
// }

// void backButtonPressed(lv_event_t * e)
// {
// 	// Your code here
// }

// void micValueChanged(lv_event_t * e)
// {
// 	// Your code here
// }

// void Ch2Pressed(lv_event_t * e)
// {
// 	// Your code here
// }

// void Ch3Pressed(lv_event_t * e)
// {
// 	// Your code here
// }

// void Ch4Pressed(lv_event_t * e)
// {
// 	// Your code here
// }

// void Ch5Pressed(lv_event_t * e)
// {
// 	// Your code here
// }

// void Ch6Pressed(lv_event_t * e)
// {
// 	// Your code here
// }

// void Ch7Pressed(lv_event_t * e)
// {
// 	// Your code here
// }

// void Ch8Pressed(lv_event_t * e)
// {
// 	// Your code here
// }

// void refValueChanged(lv_event_t * e)
// {
// 	// Your code here
// }

// void bypassValueChanged(lv_event_t * e)
// {
// 	// Your code here
// }

// void outValueChanged(lv_event_t * e)
// {
// 	// Your code here
// }
