// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView2 = lv_tabview_create(ui_Screen5, LV_DIR_TOP, 25);
    lv_obj_set_width(ui_TabView2, 320);
    lv_obj_set_height(ui_TabView2, 240);
    lv_obj_set_align(ui_TabView2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView2, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags

    ui_mind = lv_tabview_add_tab(ui_TabView2, "minden");
    lv_obj_set_style_bg_color(ui_mind, lv_color_hex(0xD22A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mind, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea6 = lv_textarea_create(ui_mind);
    lv_obj_set_width(ui_TextArea6, 425);
    lv_obj_set_height(ui_TextArea6, 170);
    lv_obj_set_x(ui_TextArea6, -10);
    lv_obj_set_y(ui_TextArea6, 10);
    lv_obj_set_align(ui_TextArea6, LV_ALIGN_LEFT_MID);
    lv_textarea_set_text(ui_TextArea6,
                         "00. 00:05:00  099 h0v0a 500 0x22_ba_be_eb  01.\n01. 00:05:00  abba beeb 099 h0v0a 500 ");
    lv_textarea_set_placeholder_text(ui_TextArea6, "1 hivja 2, 2 bontja 1");
    lv_obj_clear_flag(ui_TextArea6, LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_style_text_font(ui_TextArea6, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_TextArea6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TextArea6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_TextArea6, &lv_font_montserrat_16, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_mind);
    lv_obj_set_width(ui_Panel10, 425);
    lv_obj_set_height(ui_Panel10, 26);
    lv_obj_set_x(ui_Panel10, -10);
    lv_obj_set_y(ui_Panel10, -7);
    lv_obj_add_flag(ui_Panel10, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, -191);
    lv_obj_set_y(ui_Label29, 0);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "sorsz.");

    ui_Label28 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, -152);
    lv_obj_set_y(ui_Label28, 0);
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "ido");

    ui_Label27 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 70);
    lv_obj_set_y(ui_Label27, 0);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "hexadec.");

    ui_Label26 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, -56);
    lv_obj_set_y(ui_Label26, 0);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "tipus");

    ui_grafikon = lv_tabview_add_tab(ui_TabView2, "Grafikon");

    ui_Chart1 = lv_chart_create(ui_grafikon);
    lv_obj_set_width(ui_Chart1, 236);
    lv_obj_set_height(ui_Chart1, 133);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_div_line_count(ui_Chart1, 5, 9);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 10, 0, 10, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
    lv_chart_series_t * ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0xFF0000),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart1_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);

}
